version: '3'

services:
  redis:
    build:
      context: .
      dockerfile: ./docker/Dockerfile_redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./convert_app/conf/redis.conf:/usr/local/etc/redis/redis.conf

  mongo_db:
    image: bitnami/mongodb:latest
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongo_db_storage:/bitnami

  convert_app:
    container_name: convert_app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - CONVERT_APP_CONFIG=/app/convert_app/conf/dev.ini
      - PYTHONPATH=/app
      - ENV=development
      - LOG_PATH=/app/logs
      - LOG_LEVEL=DEBUG
      - LOG_CONF=/app/convert_app/conf/log_config/log_config.ini
      - REDIS_HOST_ADDRESS=redis
      - REDIS_PORT_BIND=6379
      - USE_REDIS_CACHE=true
      - DATABASE_CONNECTION=mongodb://mongo_db:27017/
      - DATA_SOURCE_URL=https://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist-90d.xml
    tty: true
    stdin_open: true
    volumes:
      - ./convert_app:/app/convert_app
      - ./tests:/app/tests
      - ./logs:/app/logs
      - ./.bumpversion.cfg:/app/.bumpversion.cfg
    ports:
      - 5000:5000
    depends_on:
      - redis
      - mongo_db
